function createInputTab(gui, static)
% Fills the input tab.

	gui = guidata(gui.window);
	
	% Local config
	cfg = struct(...
			... % Styles 
		'spacing',				static.general.styles.hBox.spacing, ...
		'padding',				static.general.styles.hBox.padding, ...
		'panelBorderType',		static.general.styles.panel.borderType, ...
		'panelHighlightColor',	static.general.styles.panel.highlightColor, ...
		'panelBorderWidth',		static.general.styles.panel.borderWidth, ...
		'editBackgroundColor',	static.general.styles.edit.backgroundColor, ...
		'editEnable',			static.general.styles.edit.enable, ...
		'labelColor',			static.general.styles.label.color, ...
		'labelAlign',			static.general.styles.label.textAlign{1}, ...
			... % Geometry
		'labelWidth',			static.general.geometry.label(1), ...
		'buttonWidth',			static.general.geometry.button(1:2), ...
		'rowHeight',			static.general.geometry.row(2:3), ...
			... % Sizes
		'sizes',				[] ...
		);

	cfg.sizes = struct( ...
		'hBox',					[cfg.labelWidth -1 cfg.buttonWidth(1)], ...
		'vBox',					cfg.rowHeight(1) * [1 1 1], ...
		'buttonRow',			[-1 cfg.buttonWidth(2)], ...
		'inputLayout',			[112 112 cfg.rowHeight(2)] ...
		);

	% Measured radiation pattern
	gui.inputTab.autPanel = struct('panel', ...
		uiextras.Panel(...
			'Parent',			gui.inputTab.inputLayout, ...
			'BorderType',		cfg.panelBorderType, ...
			'HighlightColor',	cfg.panelHighlightColor, ...
			'BorderWidth',		cfg.panelBorderWidth, ...
			'Title',			[' ', static.tabs.input.autPanel.title, '  '] ...
			) ...
		);

	gui.inputTab.autPanel.vBox = uiextras.VBox(...
		'Parent',				gui.inputTab.autPanel.panel ...
		);

	% Horizontal Polarization
	gui.inputTab.autPanel.horizHBox = uiextras.HBox( ...
		'Parent',				gui.inputTab.autPanel.vBox, ...
		'Spacing',				cfg.spacing, ...
		'Padding',				cfg.padding ...
		);

	gui.inputTab.autPanel.horizLabel = uicontrol(...
		'Style',				'Text', ...
		'Parent',				gui.inputTab.autPanel.horizHBox, ...
		'HorizontalAlignment',	cfg.labelAlign, ...
		'String',				static.tabs.input.autPanel.horizLabel ...
		);

	gui.inputTab.autPanel.horizEdit = uicontrol(...
		'Style',				'Edit', ...
		'Parent',				gui.inputTab.autPanel.horizHBox, ...
		'Enable',				cfg.editEnable, ...
		'BackgroundColor',		static.general.styles.edit.backgroundColor, ...
		'String',				static.tabs.input.io.general.clickToBrowse, ...
		'ButtonDownFcn',		{@inputBrowseFile, gui, static, 'aut', 'horiz'} ...
		);

	gui.inputTab.autPanel.horizButton = uicontrol(...
		'Style',				'PushButton', ...
		'Parent',				gui.inputTab.autPanel.horizHBox, ...
		'String',				static.tabs.input.io.general.browse, ...
		'Callback',				{@inputBrowseFile, gui, static, 'aut', 'horiz'} ...
		);

	set(gui.inputTab.autPanel.horizHBox, 'Sizes', cfg.sizes.hBox);

	% Vertical polarization
	gui.inputTab.autPanel.vertHBox = uiextras.HBox( ...
		'Parent',				gui.inputTab.autPanel.vBox, ...
		'Spacing',				cfg.spacing, ...
		'Padding',				cfg.padding ...
		);

	gui.inputTab.autPanel.vertLabel = uicontrol(...
		'Style',				'Text', ...
		'Parent',				gui.inputTab.autPanel.vertHBox, ...
		'HorizontalAlignment',	cfg.labelAlign, ...
		'String',				static.tabs.input.autPanel.vertLabel ...
		);

	gui.inputTab.autPanel.vertEdit = uicontrol(...
		'Style',				'Edit', ...
		'Parent',				gui.inputTab.autPanel.vertHBox, ...
		'Enable',				cfg.editEnable, ...
		'BackgroundColor', 		static.general.styles.edit.backgroundColor, ...
		'String',				static.tabs.input.io.general.clickToBrowse, ...
		'ButtonDownFcn', 		{@inputBrowseFile, gui, static, 'aut', 'vert'} ...
		);

	gui.inputTab.autPanel.vertButton = uicontrol(...
		'Style',				'PushButton', ...
		'Parent',				gui.inputTab.autPanel.vertHBox, ...
		'String',				static.tabs.input.io.general.browse, ...
		'Callback',				{@inputBrowseFile, gui, static, 'aut', 'vert'} ...
		);
	
	set(gui.inputTab.autPanel.vertHBox, 'Sizes', cfg.sizes.hBox);

	% S-Parameters
	gui.inputTab.autPanel.sParamHBox = uiextras.HBox( ...
		'Parent',				gui.inputTab.autPanel.vBox, ...
		'Spacing',				cfg.spacing, ...
		'Padding',				cfg.padding ...
		);

	gui.inputTab.autPanel.sParamLabel = uicontrol(...
		'Style',				'Text', ...
		'Parent',				gui.inputTab.autPanel.sParamHBox, ...
		'HorizontalAlignment',	cfg.labelAlign, ...
		'String',				static.tabs.input.autPanel.sParamLabel ...
		);

	gui.inputTab.autPanel.sParamEdit = uicontrol(...
		'Style',				'Edit', ...
		'Parent',				gui.inputTab.autPanel.sParamHBox, ...
		'Enable',				cfg.editEnable, ...
		'BackgroundColor',		static.general.styles.edit.backgroundColor, ...
		'String',				static.tabs.input.io.general.clickToBrowse, ...
		'ButtonDownFcn',		{@inputBrowseFile, gui, static, 'aut', 'sParam'} ...
		);

	gui.inputTab.autPanel.sParamButton = uicontrol(...
		'Style',				'PushButton', ...
		'Parent',				gui.inputTab.autPanel.sParamHBox, ...
		'String',				static.tabs.input.io.general.browse, ...
		'Callback',				{@inputBrowseFile, gui, static, 'aut', 'sParam'} ...
		);

	set(gui.inputTab.autPanel.sParamHBox, 'Sizes', cfg.sizes.hBox);
	set(gui.inputTab.autPanel.vBox, 'Sizes', cfg.sizes.vBox);

	% Reference antenna
	gui.inputTab.refPanel = struct('panel', ...
		uiextras.Panel(...
			'Parent',			gui.inputTab.inputLayout, ...
			'BorderType',		cfg.panelBorderType, ...
			'HighlightColor',	cfg.panelHighlightColor, ...
			'BorderWidth',		cfg.panelBorderWidth, ...
			'Title',			[' ', static.tabs.input.refPanel.title, '  '] ...
			) ...
		);

	gui.inputTab.refPanel.vBox = uiextras.VBox(...
		'Parent',				gui.inputTab.refPanel.panel ...
		);
	
	% Horizontal polarization
	gui.inputTab.refPanel.horizHBox = uiextras.HBox( ...
		'Parent',				gui.inputTab.refPanel.vBox, ...
		'Spacing',				cfg.spacing, ...
		'Padding',				cfg.padding ...
		);

	gui.inputTab.refPanel.horizLabel = uicontrol(...
		'Style',				'Text', ...
		'Parent',				gui.inputTab.refPanel.horizHBox, ...
		'HorizontalAlignment',	cfg.labelAlign, ...
		'String',				static.tabs.input.refPanel.horizLabel ...
		);

	gui.inputTab.refPanel.horizEdit = uicontrol(...
		'Style',				'Edit', ...
		'Parent',				gui.inputTab.refPanel.horizHBox, ...
		'Enable',				cfg.editEnable, ...
		'BackgroundColor',		static.general.styles.edit.backgroundColor, ...
		'String',				static.tabs.input.io.general.clickToBrowse, ...
		'ButtonDownFcn', 		{@inputBrowseFile, gui, static, 'ref', 'horiz'} ...
		);

	gui.inputTab.refPanel.horizButton = uicontrol(...
		'Style',				'PushButton', ...
		'Parent',				gui.inputTab.refPanel.horizHBox, ...
		'String',				static.tabs.input.io.general.browse, ...
		'Callback',				{@inputBrowseFile, gui, static, 'ref', 'horiz'} ...
		);

	set(gui.inputTab.refPanel.horizHBox, 'Sizes', cfg.sizes.hBox);

	% Vertical polarization
	gui.inputTab.refPanel.vertHBox = uiextras.HBox( ...
		'Parent',				gui.inputTab.refPanel.vBox, ...
		'Spacing',				cfg.spacing, ...
		'Padding',				cfg.padding ...
		);

	gui.inputTab.refPanel.vertLabel = uicontrol(...
		'Style',				'Text', ...
		'Parent',				gui.inputTab.refPanel.vertHBox, ...
		'HorizontalAlignment',	cfg.labelAlign, ...
		'String',				static.tabs.input.autPanel.vertLabel ...
		);

	gui.inputTab.refPanel.vertEdit = uicontrol(...
		'Style',				'Edit', ...
		'Parent',				gui.inputTab.refPanel.vertHBox, ...
		'Enable',				cfg.editEnable, ...
		'BackgroundColor',		static.general.styles.edit.backgroundColor, ...
		'String',				static.tabs.input.io.general.clickToBrowse, ...
		'ButtonDownFcn',		{@inputBrowseFile, gui, static, 'ref', 'vert'} ...
		);

	gui.inputTab.refPanel.vertButton = uicontrol(...
		'Style',				'PushButton', ...
		'Parent',				gui.inputTab.refPanel.vertHBox, ...
		'String',				static.tabs.input.io.general.browse, ...
		'Callback',				{@inputBrowseFile, gui, static, 'ref', 'vert'} ...
		);

	set(gui.inputTab.refPanel.vertHBox, 'Sizes', cfg.sizes.hBox);

	% Efficiency
	gui.inputTab.refPanel.effHBox = uiextras.HBox( ...
		'Parent',				gui.inputTab.refPanel.vBox, ...
		'Spacing',				cfg.spacing, ...
		'Padding',				cfg.padding ...
		);

	gui.inputTab.refPanel.effLabel = uicontrol(...
		'Style',				'Text', ...
		'Parent',				gui.inputTab.refPanel.effHBox, ...
		'HorizontalAlignment',	cfg.labelAlign, ...
		'String',				static.tabs.input.refPanel.effLabel ...
		);

	gui.inputTab.refPanel.effEdit = uicontrol(...
		'Style',				'Edit', ...
		'Parent',				gui.inputTab.refPanel.effHBox, ...
		'Enable',				cfg.editEnable, ...
		'BackgroundColor',		static.general.styles.edit.backgroundColor, ...
		'String',				static.tabs.input.io.general.clickToBrowse, ...
		'ButtonDownFcn',		{@inputBrowseFile, gui, static, 'ref', 'eff'} ...
		);

	gui.inputTab.refPanel.effButton = uicontrol(...
		'Style',				'PushButton', ...
		'Parent',				gui.inputTab.refPanel.effHBox, ...
		'String',				static.tabs.input.io.general.browse, ...
		'Callback',				{@inputBrowseFile, gui, static, 'ref', 'eff'} ...
		);

	set(gui.inputTab.refPanel.effHBox, 'Sizes', cfg.sizes.hBox);
	set(gui.inputTab.refPanel.vBox, 'Sizes', cfg.sizes.vBox);

	% Open button
	gui.inputTab.buttonRow = struct(...
		'hBox',				uiextras.HBox( ...
			'Parent',			gui.inputTab.inputLayout, ...
			'Spacing',			cfg.spacing, ...
			'Padding',			cfg.padding ...
			) ...
		);

	gui.inputTab.buttonRow.openLabel = uicontrol(...
		'Style',				'Text', ...
		'Parent',				gui.inputTab.buttonRow.hBox, ...
		'HorizontalAlignment',	cfg.labelAlign, ...
		'String',				'', ...
		'ForegroundColor',		cfg.labelColor ...
		);

	gui.inputTab.buttonRow.openButton = uicontrol(...
		'Style',				'PushButton', ...
		'Parent',				gui.inputTab.buttonRow.hBox, ...
		'String',				static.tabs.input.io.general.open, ...
		'Enable',				'Off', ...
		'Callback',				{@inputLoadFiles, gui, static} ...
		);

	set(gui.inputTab.buttonRow.hBox, 'Sizes', cfg.sizes.buttonRow);

	set(gui.inputTab.inputLayout, 'Sizes', cfg.sizes.inputLayout);

	guidata(gui.window, gui);

end
