function gui = createInterface(static, debug)
% Creates the main window

	% Local config
	cfg = struct(...
		'padding',		static.general.styles.main.padding, ...
		'spacing',		static.general.styles.main.spacing ...
		);

	% One struct to contain them all...
	gui = struct(...
		'dynamic',		initDynamic(static), ...
		'debug',		debug ...
		);

	% Window
	gui.window = figure(...
		'NumberTitle',  static.window.numberTitle, ...
		'Name',         static.window.name, ...
		'MenuBar',      static.window.menuBar ...
		);

	% Tabbed layout
	gui.mainLayout = uiextras.TabPanel( ...
		'Parent',       gui.window, ...
		'Padding',      cfg.padding, ...
		'Callback',		{@tabChanged, gui, static} ...
		);

	% Create tabs as VBpxes (vectical tiling as a default)
	gui.inputTab = struct('inputLayout', ...
		uiextras.VBox(...
			'Parent',   gui.mainLayout, ...
			'Padding',  cfg.padding, ...
			'Spacing',  cfg.spacing ...
			) ...
		);	

	gui.settingsTab = struct('settingsLayout', ...
		uiextras.VBox(...
			'Parent',   gui.mainLayout, ...
			'Padding',  cfg.padding, ...
			'Spacing',  cfg.spacing ...
			) ...
		);		

	gui.sParamTab = struct('sParamLayout', ...
		uiextras.VBox(...
			'Parent',   gui.mainLayout, ...
			'Padding',  cfg.padding, ...
			'Spacing',  cfg.spacing ...
			) ...
		);	

	gui.pattTab = struct('pattLayout', ... 
		uiextras.VBox(...
			'Parent',   gui.mainLayout, ...
			'Padding',  cfg.padding, ...
			'Spacing',  cfg.spacing ...
			) ...
		);	

	gui.effTab = struct('effLayout', ...
		uiextras.VBox(...
			'Parent',   gui.mainLayout, ...
			'Padding',  cfg.padding, ...
			'Spacing',  cfg.spacing ...
			) ...
		);	

	% Tab settings
	gui.mainLayout.TabNames = static.tabs.names;
	gui.mainLayout.SelectedChild = 1;
	gui.mainLayout.TabSize = static.general.geometry.tab;
	if gui.debug
		gui.mainLayout.TabEnable = repmat({'on'}, 1, length(static.tabs.enable)); 
	else
		gui.mainLayout.TabEnable = static.tabs.enable;
	end

	guidata(gui.window, gui);

	% Fill tabs
	createInputTab(gui, static);
	if gui.debug
		createSettingsTab(gui, static);
		createSParamTab(gui, static);
		createPattTab(gui, static);	
		createEffTab(gui, static);
	end

end
