function createSettingsTab(gui, static)
% Fills the settings tab.

	gui = guidata(gui.window);
	
	% Local config
 	cfg = struct(...
			... % Styles
		'padding',					static.general.styles.hBox.padding, ...
		'spacing',					static.general.styles.hBox.spacing, ...
		'panelBorderType',			static.general.styles.panel.borderType, ...
		'panelHighlightColor',		static.general.styles.panel.highlightColor, ...
		'panelBorderWidth',			static.general.styles.panel.borderWidth, ...
		'editBackgroundColor',		static.general.styles.edit.backgroundColor, ...
		'selectBackgroundColor',	static.general.styles.select.backgroundColor, ...
		'labelAlign',				{static.general.styles.label.textAlign}, ...
		'labelColor',				static.general.styles.label.color, ...
			... % Geometry
		'rowHeight',				static.general.geometry.row(2:3), ...
		'buttonWidth',				static.general.geometry.button(2), ...
		'labelWidth',				static.general.geometry.label([1 3]), ...
		'spacerWidth',				static.general.geometry.spacer(2), ...
			... % Sizes
		'sizes',					[] ...
		);
	
	cfg.sizes = struct( ...
		'unitHBox',				[cfg.labelWidth(1), -1, cfg.spacerWidth, cfg.labelWidth(1), -1], ...
		'functMethodHBox',		[cfg.labelWidth(1), -1, cfg.spacerWidth, cfg.labelWidth(1), -1], ...
		'buttonRow',			max(-1, cfg.buttonWidth * [-1 1 1]), ...
		'tableHBox',			[cfg.labelWidth(2) -1 -1 -1 -1], ...
		'tableVBox',			cfg.rowHeight(1) * ones(1, 6), ...
		'settLayout',			[48 190 cfg.rowHeight(2)] ...
		);
	
	% Global units
	gui.settingsTab.unitPanel = struct('panel', uiextras.Panel(...
		'Parent',				gui.settingsTab.settingsLayout, ...
		'BorderType',			cfg.panelBorderType, ...
		'HighlightColor',		cfg.panelHighlightColor, ...
		'BorderWidth',			cfg.panelBorderWidth, ...
		'Title',				[' ', static.tabs.settings.unitPanel.title, '  '] ...
		));	

	gui.settingsTab.unitPanel.hBox = uiextras.HBox( ...
		'Parent',				gui.settingsTab.unitPanel.panel, ...
		'Spacing',				cfg.spacing, ...
		'Padding',				cfg.padding ...
		);

	% Frequency
	gui.settingsTab.unitPanel.freqLabel = uicontrol(...
		'Style',				'Text', ...
		'Parent',				gui.settingsTab.unitPanel.hBox, ...
		'HorizontalAlignment',	cfg.labelAlign{1}, ...
		'String',				static.tabs.settings.unitPanel.freqLabel ...
		);

	gui.settingsTab.unitPanel.freqSelect = uicontrol(...
		'Style',				'Popupmenu', ...
		'Parent',				gui.settingsTab.unitPanel.hBox, ...
		'Value',				static.tabs.settings.units.freq.default, ...
		'String',				static.tabs.settings.units.freq.options, ...
		'BackgroundColor',		cfg.selectBackgroundColor, ...
		'Callback',				{@settingsUnitChange, gui, static, 'freq'} ...
		);

	gui.settingsTab.unitPanel.spacer = uiextras.Empty(...
		'Parent', 				gui.settingsTab.unitPanel.hBox);

	% Angle / phase
	gui.settingsTab.unitPanel.phaseLabel = uicontrol(...
		'Style',				'Text', ...
		'Parent',				gui.settingsTab.unitPanel.hBox, ...
		'HorizontalAlignment',	cfg.labelAlign{1}, ...
		'String',				static.tabs.settings.unitPanel.phaseLabel ...
		);

	gui.settingsTab.unitPanel.phaseSelect = uicontrol(...
		'Style',				'Popupmenu', ...
		'Parent',				gui.settingsTab.unitPanel.hBox, ...
		'Value',				static.tabs.settings.units.phase.default, ...
		'String',				static.tabs.settings.units.phase.options, ...
		'BackgroundColor',		cfg.selectBackgroundColor, ...
		'Callback',				{@settingsUnitChange, gui, static, 'phase'} ...
		);

	set(gui.settingsTab.unitPanel.hBox, 'Sizes', cfg.sizes.unitHBox);

	% Interpolation
	gui.settingsTab.interpPanel = struct('panel', uiextras.Panel(...
		'Parent',				gui.settingsTab.settingsLayout, ...
		'BorderType',			cfg.panelBorderType, ...
		'HighlightColor',		cfg.panelHighlightColor, ...
		'BorderWidth',			cfg.panelBorderWidth, ...
		'Title',				[' ', static.tabs.settings.interpPanel.title, '  '], ...
		'Enable',				'Off' ...
		));

	gui.settingsTab.interpPanel.vBox = uiextras.VBox(...
		'Parent',				gui.settingsTab.interpPanel.panel ...
		);

	% Function / Method
	gui.settingsTab.interpPanel.functMethodHBox = uiextras.HBox( ...
		'Parent',				gui.settingsTab.interpPanel.vBox, ...
		'Spacing',				cfg.spacing, ...
		'Padding',				cfg.padding ...
		);
	
	% Function
	gui.settingsTab.interpPanel.functLabel = uicontrol(...
		'Style',				'Text', ...
		'Parent',				gui.settingsTab.interpPanel.functMethodHBox, ...
		'HorizontalAlignment',	cfg.labelAlign{1}, ...
		'String',				static.tabs.settings.interpPanel.funcLabel ...
		);

	gui.settingsTab.interpPanel.functSelect = uicontrol(...
		'Style',				'Popupmenu', ...
		'Parent',				gui.settingsTab.interpPanel.functMethodHBox, ...
		'Value',				static.tabs.settings.interp.function.default, ...
		'String',				static.tabs.settings.interp.function.options, ...
		'BackgroundColor',		cfg.selectBackgroundColor ...
		); 

	gui.settingsTab.interpPanel.functMethodSpacer = uiextras.Empty( ...
		'Parent',				gui.settingsTab.interpPanel.functMethodHBox);

	% Method
	gui.settingsTab.interpPanel.methodLabel = uicontrol(...
		'Style',				'Text', ...
		'Parent',				gui.settingsTab.interpPanel.functMethodHBox, ...
		'HorizontalAlignment',	cfg.labelAlign{1}, ...
		'String',				static.tabs.settings.interpPanel.methodLabel ...
		);

	gui.settingsTab.interpPanel.methodSelect = uicontrol(...
		'Style',				'Popupmenu', ...
		'Parent',				gui.settingsTab.interpPanel.functMethodHBox, ...
		'Value',				static.tabs.settings.interp.method.default, ...
		'String',				static.tabs.settings.interp.method.options, ...
		'BackgroundColor',		cfg.selectBackgroundColor ...
		); 

	set(gui.settingsTab.interpPanel.functMethodHBox, 'Sizes', cfg.sizes.functMethodHBox);
	
	% First row: Title
	gui.settingsTab.interpPanel.titleHBox = uiextras.HBox( ...
		'Parent',				gui.settingsTab.interpPanel.vBox, ...
		'Spacing',				cfg.spacing, ...
		'Padding',				cfg.padding ...
		);

	gui.settingsTab.interpPanel.titleSpacer = uiextras.Empty( ...
		'Parent',				gui.settingsTab.interpPanel.titleHBox);

	gui.settingsTab.interpPanel.minLabel = uicontrol(...
		'Style',				'Text', ...
		'Parent',				gui.settingsTab.interpPanel.titleHBox, ...
		'HorizontalAlignment',	cfg.labelAlign{2}, ...
		'String',				static.tabs.settings.interpPanel.minLabel ...
		);

	gui.settingsTab.interpPanel.maxLabel = uicontrol(...
		'Style',				'Text', ...
		'Parent',				gui.settingsTab.interpPanel.titleHBox, ...
		'HorizontalAlignment',	cfg.labelAlign{2}, ...
		'String',				static.tabs.settings.interpPanel.maxLabel ...
		);

	gui.settingsTab.interpPanel.stepLabel = uicontrol(...
		'Style',				'Text', ...
		'Parent',				gui.settingsTab.interpPanel.titleHBox, ...
		'HorizontalAlignment',	cfg.labelAlign{2}, ...
		'String',				static.tabs.settings.interpPanel.stepLabel ...
		);

	gui.settingsTab.interpPanel.countLabel = uicontrol(...
		'Style',				'Text', ...
		'Parent',				gui.settingsTab.interpPanel.titleHBox, ...
		'HorizontalAlignment',	cfg.labelAlign{2}, ...
		'String',				static.tabs.settings.interpPanel.countLabel ...
		);
	
	set(gui.settingsTab.interpPanel.titleHBox, 'Sizes', cfg.sizes.tableHBox);

	% Second row: Frequency	
	gui.settingsTab.interpPanel.freqHBox = uiextras.HBox( ...
		'Parent',				gui.settingsTab.interpPanel.vBox, ...
		'Spacing',				cfg.spacing, ...
		'Padding',				cfg.padding ...
		);

	gui.settingsTab.interpPanel.freqLabel = uicontrol(...
		'Style',				'Text', ...
		'Parent',				gui.settingsTab.interpPanel.freqHBox, ...
		'HorizontalAlignment',	cfg.labelAlign{1}, ...
		'String',				sprintf(static.tabs.sParam.settPanel.freqLabel, ...
									static.tabs.settings.units.freq.units{...
									static.tabs.settings.units.freq.default}) ...
		);

	gui.settingsTab.interpPanel.freqMinEdit = uicontrol(...
		'Style',				'Edit', ...
		'Parent',				gui.settingsTab.interpPanel.freqHBox, ...
		'String',				'', ...
		'BackgroundColor',		cfg.editBackgroundColor, ...
		'Callback',				{@settingsInterpChange, gui, static, 'freq', false} ...
		);

	gui.settingsTab.interpPanel.freqMaxEdit = uicontrol(...
		'Style',				'Edit', ...
		'Parent',				gui.settingsTab.interpPanel.freqHBox, ...
		'String',				'', ...
		'BackgroundColor',		cfg.editBackgroundColor, ...
		'Callback',				{@settingsInterpChange, gui, static, 'freq', false} ...
		);

	gui.settingsTab.interpPanel.freqStepEdit = uicontrol(...
		'Style',				'Edit', ...
		'Parent',				gui.settingsTab.interpPanel.freqHBox, ...
		'String',				'', ...
		'BackgroundColor',		cfg.editBackgroundColor, ...
		'Callback',				{@settingsInterpChange, gui, static, 'freq', false} ...
		);

	gui.settingsTab.interpPanel.freqCountEdit = uicontrol(...
		'Style',				'Edit', ...
		'Parent',				gui.settingsTab.interpPanel.freqHBox, ...
		'String',				'', ...
		'BackgroundColor',		cfg.editBackgroundColor, ...
		'Callback',				{@settingsInterpChange, gui, static, 'freq', true} ...
		);
	
	set(gui.settingsTab.interpPanel.freqHBox, 'Sizes', cfg.sizes.tableHBox);

	% Third row: Primary
	gui.settingsTab.interpPanel.primHBox = uiextras.HBox( ...
		'Parent',				gui.settingsTab.interpPanel.vBox, ...
		'Spacing',				cfg.spacing, ...
		'Padding',				cfg.padding ...
		);

	gui.settingsTab.interpPanel.primLabel = uicontrol(...
		'Style',				'Text', ...
		'Parent',				gui.settingsTab.interpPanel.primHBox, ...
		'HorizontalAlignment',	cfg.labelAlign{1}, ...
		'String',				sprintf(static.tabs.settings.interpPanel.primLabel, ...
									static.tabs.settings.units.phase.units{...
										static.tabs.settings.units.phase.default}) ...
		);

	gui.settingsTab.interpPanel.primMinEdit = uicontrol(...
		'Style',				'Edit', ...
		'Parent',				gui.settingsTab.interpPanel.primHBox, ...
		'String',				'', ...
		'BackgroundColor',		cfg.editBackgroundColor, ...
		'Callback', 			{@settingsInterpChange, gui, static, 'prim', false} ...
		);

	gui.settingsTab.interpPanel.primMaxEdit = uicontrol(...
		'Style',				'Edit', ...
		'Parent',				gui.settingsTab.interpPanel.primHBox, ...
		'String',				'', ...
		'BackgroundColor',		cfg.editBackgroundColor, ...
		'Callback',				{@settingsInterpChange, gui, static, 'prim', false} ...
		);

	gui.settingsTab.interpPanel.primStepEdit = uicontrol(...
		'Style',				'Edit', ...
		'Parent',				gui.settingsTab.interpPanel.primHBox, ...
		'String',				'', ...
		'BackgroundColor',		cfg.editBackgroundColor, ...
		'Callback',				{@settingsInterpChange, gui, static, 'prim', false} ...
		);

	gui.settingsTab.interpPanel.primCountEdit = uicontrol(...
		'Style',				'Edit', ...
		'Parent',				gui.settingsTab.interpPanel.primHBox, ...
		'String',				'', ...
		'BackgroundColor',		cfg.editBackgroundColor, ...
		'Callback',				{@settingsInterpChange, gui, static, 'prim', true} ...
		);
	
	set(gui.settingsTab.interpPanel.primHBox, 'Sizes', cfg.sizes.tableHBox);

	% Fourth row: Secondary
	gui.settingsTab.interpPanel.secHBox = uiextras.HBox( ...
		'Parent',				gui.settingsTab.interpPanel.vBox, ...
		'Spacing',				cfg.spacing, ...
		'Padding',				cfg.padding ...
		);

	gui.settingsTab.interpPanel.secLabel = uicontrol(...
		'Style',				'Text', ...
		'Parent',				gui.settingsTab.interpPanel.secHBox, ...
		'HorizontalAlignment',	cfg.labelAlign{1}, ...
		'String',				sprintf(static.tabs.settings.interpPanel.secLabel, ...
									static.tabs.settings.units.phase.units{...
									static.tabs.settings.units.phase.default}) ...
		);

	gui.settingsTab.interpPanel.secMinEdit = uicontrol(...
		'Style',				'Edit', ...
		'Parent',				gui.settingsTab.interpPanel.secHBox, ...
		'String',				'', ...
		'BackgroundColor',		cfg.editBackgroundColor, ...
		'Callback',				{@settingsInterpChange, gui, static, 'sec', false} ...
		);

	gui.settingsTab.interpPanel.secMaxEdit = uicontrol(...
		'Style',				'Edit', ...
		'Parent',				gui.settingsTab.interpPanel.secHBox, ...
		'String',				'', ...
		'BackgroundColor',		cfg.editBackgroundColor, ...
		'Callback',				{@settingsInterpChange, gui, static, 'sec', false} ...
		);

	gui.settingsTab.interpPanel.secStepEdit = uicontrol(...
		'Style',				'Edit', ...
		'Parent',				gui.settingsTab.interpPanel.secHBox, ...
		'String',				'', ...
		'BackgroundColor',		cfg.editBackgroundColor, ...
		'Callback',				{@settingsInterpChange, gui, static, 'sec', false} ...
		);

	gui.settingsTab.interpPanel.secCountEdit = uicontrol(...
		'Style',				'Edit', ...
		'Parent',				gui.settingsTab.interpPanel.secHBox, ...
		'String',				'', ...
		'BackgroundColor',		cfg.editBackgroundColor, ...
		'Callback',				{@settingsInterpChange, gui, static, 'sec', true} ...
		);
	
	set(gui.settingsTab.interpPanel.secHBox, 'Sizes', cfg.sizes.tableHBox);

	% Fifth row
	gui.settingsTab.interpPanel.totalHBox = uiextras.HBox( ...
		'Parent',				gui.settingsTab.interpPanel.vBox, ...
		'Spacing',				cfg.spacing, ...
		'Padding',				cfg.padding ...
		);

	gui.settingsTab.interpPanel.totalSpacer1 = uiextras.Empty( ...
		'Parent',				gui.settingsTab.interpPanel.totalHBox);

	gui.settingsTab.interpPanel.totalSpacer2 = uiextras.Empty( ...
		'Parent',				gui.settingsTab.interpPanel.totalHBox);

	gui.settingsTab.interpPanel.totalSpacer3 = uiextras.Empty( ...
		'Parent',				gui.settingsTab.interpPanel.totalHBox);

	gui.settingsTab.interpPanel.totalLabel = uicontrol(...
		'Style',				'Text', ...
		'Parent',				gui.settingsTab.interpPanel.totalHBox, ...
		'HorizontalAlignment',	cfg.labelAlign{2}, ...
		'String',				static.tabs.settings.interpPanel.totalLabel ...
		);

	gui.settingsTab.interpPanel.totalEdit = uicontrol(...
		'Style',				'Edit', ...
		'Parent',				gui.settingsTab.interpPanel.totalHBox, ...
		'String',				'', ...
		'BackgroundColor',		cfg.editBackgroundColor, ...
		'Enable',				static.general.styles.edit.enable ...
		);
	
	set(gui.settingsTab.interpPanel.totalHBox, 'Sizes', cfg.sizes.tableHBox);

	set(gui.settingsTab.interpPanel.vBox, 'Sizes',	cfg.sizes.tableVBox);

	% Buttons
	gui.settingsTab.buttonRow = struct('hBox', uiextras.HBox( ...
		'Parent',				gui.settingsTab.settingsLayout, ...
		'Spacing',				cfg.spacing, ...
		'Padding',				cfg.padding ...
		));

	gui.settingsTab.buttonRow.buttonLabel = uicontrol(...
		'Style',				'Text', ...
		'Parent',				gui.settingsTab.buttonRow.hBox, ...
		'HorizontalAlignment',	cfg.labelAlign{2}, ...
		'String',				'', ...
		'ForegroundColor',		cfg.labelColor ...
		);

	gui.settingsTab.buttonRow.defaultsButton = uicontrol(...
		'Style',				'PushButton', ...
		'Parent',				gui.settingsTab.buttonRow.hBox, ...
		'String',				static.tabs.settings.buttonHBox.defaults, ...
		'Callback',				{@settingsDefault, gui, static} ...
		);

	gui.settingsTab.buttonRow.saveButton = uicontrol(...
		'Style',				'PushButton', ...
		'Parent',				gui.settingsTab.buttonRow.hBox, ...
		'String',				static.tabs.settings.buttonHBox.save, ...
		'Callback',				{@settingsSave, gui, static} ...
		);

	set(gui.settingsTab.buttonRow.hBox, 'Sizes', cfg.sizes.buttonRow);
	
	set(gui.settingsTab.settingsLayout, 'Sizes', cfg.sizes.settLayout);

	guidata(gui.window, gui);

end
