function createEffTab(gui, static)
% Fill the efficiency tab.

	gui = guidata(gui.window);
	
	% Local config (to enable overrides)
 	cfg = struct( ...
			... % Styles
		'padding',					static.general.styles.hBox.padding, ...
		'spacing',					static.general.styles.hBox.spacing, ...
		'panelBorderType',			static.general.styles.panel.borderType, ...
		'panelHighlightColor',		static.general.styles.panel.highlightColor, ...
		'panelBorderWidth',			static.general.styles.panel.borderWidth, ...
		'editBackgroundColor',		static.general.styles.edit.backgroundColor, ...
		'selectBackgroundColor',	static.general.styles.select.backgroundColor, ...
		'labelAlign',				static.general.styles.label.textAlign{1}, ...
			... % Geometry
		'buttonWidth',				static.general.geometry.button(2), ...
		'rowHeight',				static.general.geometry.row(2:3), ...
		'labelWidth',				static.general.geometry.label(1), ...
		'spacerWidth',				static.general.geometry.spacer(3), ...
			... % Sizes
		'sizes',					[] ...
		);

	cfg.sizes = struct( ...
		'exportPanel',				[-1 cfg.buttonWidth], ...
		'topHBox',					[cfg.labelWidth -1 cfg.spacerWidth cfg.labelWidth -1], ...
		'buttonHBox',				max(-1, cfg.buttonWidth * [1 -1 1 1]), ...
		'settPanel',				cfg.rowHeight, ...
		'effLayout',				[50 90 -1] ...
		);
	
	% Export
	gui.effTab.exportPanel = struct('panel', uiextras.Panel(...
		'Parent',				gui.effTab.effLayout, ...
		'BorderType',			cfg.panelBorderType, ...
		'HighlightColor',		cfg.panelHighlightColor, ...
		'BorderWidth',			cfg.panelBorderWidth, ...
		'Title',				[' ', static.tabs.eff.expPanel.title, '  '] ...
		));
	
	gui.effTab.exportPanel.hBox = uiextras.HBox( ...
		'Parent',				gui.effTab.exportPanel.panel, ...
		'Spacing',				cfg.spacing, ...
		'Padding',				cfg.padding ...
		);
	
	gui.effTab.exportPanel.exportLabel = uicontrol(...
		'Style',				'Text', ...
		'Parent',				gui.effTab.exportPanel.hBox, ...
		'HorizontalAlignment',	cfg.labelAlign, ...
		'String',				static.tabs.eff.expPanel.saveLabel ...
		);
	
	gui.effTab.exportPanel.exportButton = uicontrol(...
		'Style',				'PushButton', ...
		'Parent',				gui.effTab.exportPanel.hBox, ...
		'String',				static.tabs.eff.expPanel.expButt, ...
		'Callback',				{@effExport, gui, static} ...
		);
	
	set(gui.effTab.exportPanel.hBox, 'Sizes', cfg.sizes.exportPanel);

	% Plot settings
	gui.effTab.settPanel = struct('panel', uiextras.Panel(...
		'Parent',				gui.effTab.effLayout, ...
		'BorderType',			cfg.panelBorderType, ...
		'HighlightColor',		cfg.panelHighlightColor, ...
		'BorderWidth',			cfg.panelBorderWidth, ...
		'Title',				[' ', static.tabs.eff.settPanel.title, '  '] ...
		));

	gui.effTab.settPanel.vBox = uiextras.VBox( ...
		'Parent',				gui.effTab.settPanel.panel ...
		);

	gui.effTab.settPanel.topHBox = uiextras.HBox( ...
		'Parent',				gui.effTab.settPanel.vBox, ...
		'Spacing',				cfg.spacing, ...
		'Padding',				cfg.padding ...
		);

	% Unit
	gui.effTab.settPanel.unitLabel = uicontrol(...
		'Style',				'Text', ...
		'Parent',				gui.effTab.settPanel.topHBox, ...
		'HorizontalAlignment',	cfg.labelAlign, ...
		'String',				static.tabs.eff.settPanel.unitLabel ...
		);

	gui.effTab.settPanel.unitSelect = uicontrol(...
		'Style',				'Popupmenu', ...
		'Parent',				gui.effTab.settPanel.topHBox, ...
		'String',				static.tabs.eff.plotSett.unit.options, ...
		'Value',				static.tabs.eff.plotSett.unit.default, ...
		'BackgroundColor',		static.general.styles.edit.backgroundColor ...
		); 

	gui.effTab.settPanel.topSpacer = uiextras.Empty( ...
		'Parent',				gui.effTab.settPanel.topHBox);

	% Replacement
	gui.effTab.settPanel.replacementLabel = uicontrol(...
		'Style',				'Text', ...
		'Parent',				gui.effTab.settPanel.topHBox, ...
		'HorizontalAlignment',	cfg.labelAlign, ...
		'String',				static.tabs.eff.settPanel.replLabel ...
		);

	gui.effTab.settPanel.replacementSelect = uicontrol(...
		'Style',				'Popupmenu', ...
		'Parent',				gui.effTab.settPanel.topHBox, ...
		'String',				static.tabs.eff.plotSett.replacement.options, ...
		'Value',				static.tabs.eff.plotSett.replacement.default, ...
		'BackgroundColor',		static.general.styles.edit.backgroundColor ...
		); 

	set(gui.effTab.settPanel.topHBox, 'Sizes', cfg.sizes.topHBox);

	gui.effTab.settPanel.buttonHBox = uiextras.HBox( ...
		'Parent',				gui.effTab.settPanel.vBox, ...
		'Spacing',				cfg.spacing, ...
		'Padding',				cfg.padding ...
		);

	gui.effTab.settPanel.popButton = uicontrol(...
		'Style',				'PushButton', ...
		'Parent',				gui.effTab.settPanel.buttonHBox, ...
		'String',				static.tabs.eff.settPanel.popButt, ...
		'Callback',				{@effPop, gui, static}, ...
		'Enable',				'Off' ...
		);

	gui.effTab.settPanel.buttonSpacer = uiextras.Empty( ...
		'Parent',				gui.effTab.settPanel.buttonHBox);

	gui.effTab.settPanel.defaultsButton = uicontrol(...
		'Style',				'PushButton', ...
		'Parent',				gui.effTab.settPanel.buttonHBox, ...
		'String',				static.tabs.eff.settPanel.defButt, ...
		'Callback',				{@effDefaults, gui, static} ...
		);

	gui.effTab.settPanel.plotButton = uicontrol(...
		'Style',				'PushButton', ...
		'Parent',				gui.effTab.settPanel.buttonHBox, ...
		'String',				static.tabs.eff.settPanel.plotButt, ...
		'Callback',				{@effPlot, gui, static} ...
		);

	set(gui.effTab.settPanel.buttonHBox, 'Sizes', cfg.sizes.buttonHBox);

	set(gui.effTab.settPanel.vBox, 'Sizes', cfg.sizes.settPanel);

	% Graph
	gui.effTab.graphPanel = struct('panel', uiextras.Panel(...
		'Parent',				gui.effTab.effLayout, ...
		'BorderType',			cfg.panelBorderType, ...
		'HighlightColor',		cfg.panelHighlightColor, ...
		'BorderWidth',			cfg.panelBorderWidth, ...
		'Padding',				cfg.padding, ...
		'Title',				[' ', static.tabs.eff.graphPanel.title, '  '] ...
		));

	gui.effTab.graphPanel.axes = axes( ...
		'Parent',					gui.effTab.graphPanel.panel, ...
		'ActivePositionProperty',	'OuterPosition', ...
		'Visible',					'Off' ...
		);
	
	gui.effTab.graphPanel.legend = struct( ...
		'enable',	false, ...
		'handles',	[], ...
		'markers',	[], ...
		'text',		{{}} ...
		);

	set(gui.effTab.effLayout, 'Sizes', cfg.sizes.effLayout);

	guidata(gui.window, gui);

end
