function createSParamTab(gui, static)
% Fills the S-parameters tab.

	gui = guidata(gui.window);
	
	% Local config
 	cfg = struct(...
			... % Styles
		'padding',					static.general.styles.hBox.padding, ...
		'spacing',					static.general.styles.hBox.spacing, ...
		'panelBorderType',			static.general.styles.panel.borderType, ...
		'panelHighlightColor',		static.general.styles.panel.highlightColor, ...
		'panelBorderWidth',			static.general.styles.panel.borderWidth, ...
		'editBackgroundColor',		static.general.styles.edit.backgroundColor, ...
		'selectBackgroundColor',	static.general.styles.select.backgroundColor, ...
		'listBackgroundColor',		static.general.styles.list.backgroundColor, ...
		'labelAlign',				static.general.styles.label.textAlign{1}, ...
			... % Geometry
		'buttonWidth',				static.general.geometry.button(2), ...
		'labelWidth',				static.general.geometry.label(3), ...
		'spacerWidth',				static.general.geometry.spacer(1), ...
		'rowHeight',				static.general.geometry.row, ...
			... % Sizes
		'sizes',					[] ...	
		);
		
	cfg.sizes = struct( ...
		'freqHBox',					[cfg.labelWidth -1 cfg.spacerWidth -1], ...
		'leftHBox',					[cfg.labelWidth -1], ...
		'leftVBox',					cfg.rowHeight(2) * [1 1 1], ...
		'rightVBox',				[cfg.rowHeight(1) -1], ...
		'topHBox',					[-5 -3], ...
		'buttonHBox',				max(-1, cfg.buttonWidth * [1 -1 1 1]), ...
		'settPanel',				[100 35], ...
		'sParamLayout',				[140 -1] ...
		);
	
	% Plot settings
	gui.sParamTab.settPanel = struct('panel', uiextras.Panel(...
		'Parent',				gui.sParamTab.sParamLayout, ...
		'BorderType',			cfg.panelBorderType, ...
		'HighlightColor',		cfg.panelHighlightColor, ...
		'BorderWidth',			cfg.panelBorderWidth, ...
		'Title',				[' ', static.tabs.sParam.settPanel.title, '  '] ...
		));

	% VBox for top_ and button_
	% HBox for left_ and right_
	% VBox for individual rows (on the left)
	gui.sParamTab.settPanel.vBox = uiextras.VBox(...
		'Parent',				gui.sParamTab.settPanel.panel ...
		);

	gui.sParamTab.settPanel.topHBox = uiextras.HBox(...
		'Parent',				gui.sParamTab.settPanel.vBox ...
		);

	gui.sParamTab.settPanel.leftVBox = uiextras.VBox(...
		'Parent',				gui.sParamTab.settPanel.topHBox ...
		);

	% Frequency
	gui.sParamTab.settPanel.freqHBox = uiextras.HBox( ...
		'Parent',				gui.sParamTab.settPanel.leftVBox, ...
		'Spacing',				cfg.spacing, ...
		'Padding',				cfg.padding ...
		);

	gui.sParamTab.settPanel.freqLabel = uicontrol(...
		'Style',				'Text', ...
		'Parent',				gui.sParamTab.settPanel.freqHBox, ...
		'HorizontalAlignment',	cfg.labelAlign, ...
		'String',				sprintf(static.tabs.sParam.settPanel.freqLabel, ...
									static.tabs.settings.units.freq.units{...
										static.tabs.settings.units.freq.default}) ...
		);

	gui.sParamTab.settPanel.freqMinEdit = uicontrol(...
		'Style',				'Edit', ...
		'Parent',				gui.sParamTab.settPanel.freqHBox, ...
		'String',				'', ...
		'CallBack',				{@scattChangeFreq, gui, static}, ...
		'BackgroundColor',		cfg.editBackgroundColor ...
		);

	gui.sParamTab.settPanel.freqSpacerLabel = uicontrol(...
		'Style',				'Text', ...
		'Parent',				gui.sParamTab.settPanel.freqHBox, ...
		'HorizontalAlignment',	'center', ...
		'String',				'-' ...
		); 

	gui.sParamTab.settPanel.freqMaxEdit = uicontrol(...
		'Style',				'Edit', ...
		'Parent',				gui.sParamTab.settPanel.freqHBox, ...
		'String',				'', ...
		'CallBack',				{@scattChangeFreq, gui, static}, ...
		'BackgroundColor',		cfg.editBackgroundColor ...
		);

	set(gui.sParamTab.settPanel.freqHBox, 'Sizes', cfg.sizes.freqHBox);

	% Graph type
	gui.sParamTab.settPanel.graphHBox = uiextras.HBox( ...
		'Parent',				gui.sParamTab.settPanel.leftVBox, ...
		'Spacing',				cfg.spacing, ...
		'Padding',				cfg.padding ...
		);

	gui.sParamTab.settPanel.graphLabel = uicontrol(...
		'Style',				'Text', ...
		'Parent',				gui.sParamTab.settPanel.graphHBox, ...
		'HorizontalAlignment',	cfg.labelAlign, ...
		'String',				static.tabs.sParam.settPanel.graphLabel ...
		);

	gui.sParamTab.settPanel.graphSelect = uicontrol(...
		'Style',				'Popupmenu', ...
		'Parent',				gui.sParamTab.settPanel.graphHBox, ...
		'String',				static.tabs.sParam.plotSett.graphType.options, ...
		'Value',				static.tabs.sParam.plotSett.graphType.default, ...
		'Callback',				{@scattChangeGraph, gui}, ...
		'BackgroundColor',		cfg.selectBackgroundColor ...
		); 

	set(gui.sParamTab.settPanel.graphHBox, 'Sizes', cfg.sizes.leftHBox);

	% Replacement
	gui.sParamTab.settPanel.replacementHBox = uiextras.HBox( ...
		'Parent',				gui.sParamTab.settPanel.leftVBox, ...
		'Spacing',				cfg.spacing, ...
		'Padding',				cfg.padding ...
		);

	gui.sParamTab.settPanel.replacementLabel = uicontrol(...
		'Style',				'Text', ...
		'Parent',				gui.sParamTab.settPanel.replacementHBox, ...
		'HorizontalAlignment',	cfg.labelAlign, ...
		'String',				static.tabs.sParam.settPanel.replLabel ...
		);

	gui.sParamTab.settPanel.replacementSelect = uicontrol(...
		'Style',				'Popupmenu', ...
		'Parent',				gui.sParamTab.settPanel.replacementHBox, ...
		'String',				static.tabs.sParam.plotSett.replacement.options, ...
		'Value',				static.tabs.sParam.plotSett.replacement.default, ...
		'Enable',				'on', ...
		'BackgroundColor',		cfg.selectBackgroundColor ...
		); 

	set(gui.sParamTab.settPanel.replacementHBox, 'Sizes', cfg.sizes.leftHBox);

	set(gui.sParamTab.settPanel.leftVBox, 'Sizes', cfg.sizes.leftVBox);

	% Marker-list
	gui.sParamTab.settPanel.rightVBox = uiextras.VBox( ...
		'Parent',				gui.sParamTab.settPanel.topHBox, ...
		'Spacing',				cfg.spacing, ...
		'Padding',				cfg.padding ...
		);

	gui.sParamTab.settPanel.markerLabel = uicontrol(...
		'Style',				'Text', ...
		'Parent',				gui.sParamTab.settPanel.rightVBox, ...
		'HorizontalAlignment',	cfg.labelAlign, ...
		'String',				static.tabs.sParam.settPanel.markerLabel ...
		);

	gui.sParamTab.settPanel.markerList = uicontrol(...
		'Style',				'ListBox', ...
		'Parent',				gui.sParamTab.settPanel.rightVBox, ...
		'String',				static.tabs.sParam.plotSett.marker.options, ...
		'Value',				static.tabs.sParam.plotSett.marker.default, ...
		'Min',					static.tabs.sParam.plotSett.marker.default, ...
		'Max',					static.tabs.sParam.plotSett.marker.default, ...
		'CallBack',				{@scattChangeMarker, gui}, ...
		'BackgroundColor',		cfg.listBackgroundColor ...
		); 

	set(gui.sParamTab.settPanel.rightVBox, 'Sizes', cfg.sizes.rightVBox);

	set(gui.sParamTab.settPanel.topHBox, 'Sizes', cfg.sizes.topHBox);

	% Buttons
	gui.sParamTab.settPanel.buttonHBox = uiextras.HBox( ...
		'Parent',				gui.sParamTab.settPanel.vBox, ...
		'Spacing',				cfg.spacing, ...
		'Padding',				cfg.padding ...
		);

	gui.sParamTab.settPanel.popButton = uicontrol(...
		'Style',				'PushButton', ...
		'Parent',				gui.sParamTab.settPanel.buttonHBox, ...
		'CallBack',				{@scattPop, gui, static}, ...
		'String',				static.tabs.sParam.settPanel.popButt, ...
		'Enable',				'Off' ...
		);

	gui.sParamTab.settPanel.buttonSpacer = uiextras.Empty( ...
		'Parent',				gui.sParamTab.settPanel.buttonHBox);

	gui.sParamTab.settPanel.defaultsButton = uicontrol(...
		'Style',				'PushButton', ...
		'Parent',				gui.sParamTab.settPanel.buttonHBox, ...
		'CallBack',				{@scattDefaults, gui, static}, ...
		'String',				static.tabs.sParam.settPanel.defButt ...
		);

	gui.sParamTab.settPanel.plotButton = uicontrol(...
		'Style',				'PushButton', ...
		'Parent',				gui.sParamTab.settPanel.buttonHBox, ...
		'CallBack',				{@scattPlot, gui, static}, ...
		'String',				static.tabs.sParam.settPanel.plotButt ...
		);

	set(gui.sParamTab.settPanel.buttonHBox, 'Sizes', cfg.sizes.buttonHBox);

	set(gui.sParamTab.settPanel.vBox, 'Sizes', cfg.sizes.settPanel);

	% Graph
	gui.sParamTab.graphPanel = struct('panel', uiextras.Panel(...
		'Parent',				gui.sParamTab.sParamLayout, ...
		'BorderType',			cfg.panelBorderType, ...
		'HighlightColor',		cfg.panelHighlightColor, ...
		'BorderWidth',			cfg.panelBorderWidth, ...
		'Padding',				cfg.padding, ...
		'Title',				[' ', static.tabs.sParam.graphPanel.title, '  '] ...
		));

	gui.sParamTab.graphPanel.axes = axes( ...
		'Parent',					gui.sParamTab.graphPanel.panel, ...
		'ActivePositionProperty',	'OuterPosition', ...
		'Visible',					'Off');
	
	gui.sParamTab.graphPanel.smith = false;
	
	gui.sParamTab.graphPanel.legend = struct( ...
		'enable',	false, ...
		'handles',	[], ...
		'markers',	[], ...
		'text',		{{}} ...
		);

	set(gui.sParamTab.sParamLayout, 'Sizes', cfg.sizes.sParamLayout);
	
	guidata(gui.window, gui);

end
