function [s] = initStatic()
% [S] = INITSTATIC Initialize static data
%	Initializes the static data struct used by antMeas.

	str = readStrings('en');
	
	s = struct( ...
		'window',		struct( ...
			'name',			str.winTitle, ...
			'numberTitle',	'off', ...
			'menuBar',		'none' ...
			), ...
		'general',		struct( ...
			'date',			struct( ...
				'full',			'ddd dd.mm.yyyy, HH:MM', ...
				'clock',		'HH:MM', ...
				'date',			'dd.mm.yyyy' ...
				), ...
			'geometry',		struct( ...
				'row',			[12 30 35], ...
				'button',		[75 100], ...
				'label',		[75 100 125], ...
				'tab',			100, ...
				'spacer',		[15 20 25] ...
				), ...
			'styles',		struct( ...
				'main',			struct( ...
					'padding',			5, ...
					'spacing',			15 ...
					), ...
				'edit',			struct( ...
					'backgroundColor',	1 * [1 1 1], ...
					'enable',		'inactive' ...
					), ...
				'select',			struct( ...
					'backgroundColor',	1 * [1 1 1] ...
					), ...
				'list',			struct( ...
					'backgroundColor',	1 * [1 1 1] ...
					), ...
				'panel',		struct( ...
					'borderType',		'line', ...
					'borderWidth',		1, ...
					'highlightColor',	0.5 * [1 1 1], ...
					'padding',			0, ...
					'spacing',			0 ...
					), ...
				'hBox',			struct( ...
					'padding',			5, ...
					'spacing',			5 ...
					), ...
				'vBox',			struct( ...
					'padding',			0, ...
					'spacing',			0 ...
					), ...
				'label',		struct( ...
					'textAlign',		{{'left', 'center'}}, ...
					'color',		[1 0 0] ...
					) ...
				) ...
			), ...
		'tabs',			struct( ...
			'names',		{{str.tabInput, str.tabSett, str.tabScatt, ...
								str.tabPatt, str.tabEff}}, ...
			'enable',		{{'on', 'off', 'off', 'off', 'off'}}, ...
			'input',		struct( ...
				'io',		struct( ...
					'general',			struct( ...
						'clickToBrowse',	str.ioClickToBrowse, ...
						'browse',			str.buttonBrowse, ...
						'dialogTitle',		str.ioDialogTitle, ...
						'open',				str.buttonOpen, ...
						'antenna',			struct( ...
							'aut',				str.ioAntAut, ...
							'ref',				str.ioAntRef ...
							) ...
						), ...
					'horiz',			struct( ...
						'ext',				'*.001', ...
						'desc',				str.ioFileTypePatt, ...
						'meas',				str.ioMeasHoriz ...
						), ...
					'vert',			struct( ...
						'ext',				'*.001', ...
						'desc',				str.ioFileTypePatt, ...
						'meas',				str.ioMeasVert ...
						), ...
					'sParam',		struct( ...
						'ext',				'*.s1p', ...
						'desc',				str.ioFileTypeScatt, ...
						'meas',				str.ioMeasScatt ...
						), ...
					'eff',			struct( ...
						'ext',				'*.txt', ...
						'desc',				str.ioFileTypeEff, ...
						'meas',				str.ioMeasEff ...
						) ...
					), ...
				'autPanel',		struct( ...
					'title',		str.labelAut, ...
					'horizLabel',	str.labelHoriz, ...
					'vertLabel',	str.labelVert, ...
					'sParamLabel',	str.labelScatt ...
					), ...
				'refPanel',		struct( ...
					'title',		str.labelRef, ...
					'horizLabel',	str.labelHoriz, ...
					'vertLabel',	str.labelVert, ...
					'effLabel',		str.labelEff ...
					), ...
				'errorMsg',		struct( ...
					'empty',		str.ioErrorEmpty, ...
					'same',			str.ioErrorSame, ...
					'load',			str.ioErrorLoad, ...
					'unknown',		str.ioErrorUnknown ...
					) ...
				), ...
			'settings',		struct( ...
				'interpPanel',	struct( ...
					'title',		str.labelInterp, ...
					'funcLabel',	str.labelFunction, ...
					'methodLabel',	str.labelMethod, ...
					'maxLabel',		str.labelMax, ...
					'minLabel',		str.labelMin, ...
					'stepLabel',	str.labelStep, ...
					'countLabel',	str.labelCount, ...
					'freqLabel',	str.labelFreqUnit, ...
					'primLabel',	str.labelPrimUnit, ...
					'secLabel',		str.labelSecUnit, ...
					'totalLabel',	str.labelTotal ...
					), ...
				'unitPanel',	struct( ...
					'title',		str.labelGlobalUnits,	...
					'freqLabel',	str.labelFrequency, ...
					'phaseLabel',	str.labelPhase ...
					), ...
				'buttonHBox',	struct( ...
					'defaults',		str.buttonDefaults, ...
					'save',			str.buttonSave ...
					), ...
				'errorMsg',		struct( ...
					'unknown',		str.ioErrorUnknown ...
					), ...
				'maxExtrap',	0.1, ...
				'interp',	struct( ...
					'function',		struct( ...
						'options',		{{ str.optionNearest, ...
											str.optionLinear, ...
											str.optionSpline, ...
											str.optionCubic }}, ...
						'default',		4 ...
						), ...
					'method',		struct( ...
						'options',		{{ str.optionRealImag, ...
											str.optionLinMag, ...
											str.optionLogMag }}, ...
						'default',		1 ...
						) ...
					), ...
				'units',	struct( ...
					'freq',			struct( ...
						'options',		{{ str.optionHertz, ...
											str.optionKilohertz, ...
											str.optionMegahertz, ...
											str.optionGigahertz, ...
											str.optionTerahertz }}, ...
						'units',		{{'Hz', 'kHz', 'MHz', 'GHz', 'THz'}}, ...
						'coeffs',		10 .^ [0 3 6 9 12], ...
						'default',		3 ...
						), ...
					'phase',		struct( ...
						'options',		{{ str.optionDegrees, ...
											str.optionRadians }}, ...
						'units',		{{'º', 'rad'}}, ...
						'coeffs',		[1 180/pi], ...
						'default',		1 ...
						) ...
					) ...
				), ...
			'sParam',		struct( ...
				'settPanel',	struct( ...
					'title',		str.labelPlotSett, ...
					'freqLabel',	str.labelFreqRange, ...
					'graphLabel',	str.labelGraphType, ...
					'replLabel',	str.labelReplacement, ...
					'markerLabel',	str.labelMarkerFreq, ...
					'popButt',		str.buttonPop, ...
					'defButt',		str.buttonDefaults, ...
					'plotButt',		str.buttonPlot, ...
					'noneText',		str.labelNone ...
					), ...
				'graphPanel',	struct( ...
					'title',		str.labelGraph ...
					), ...
				'annotation',	struct( ...
					'freq',			str.annFrequency, ...
					'phase',		str.annPhase, ...
					'linMag',		str.annLinMag, ...
					'logMag',		str.annLogMag, ...
					'markerFreq',	str.annMarkerFreq, ...
					'markerPhase',	str.annMarkerPhase, ...
					'markerLinMag',	str.annMarkerLinMag, ...
					'markerLogMag',	str.annMarkerLogMag ...
					), ...
				'plotSett',	struct( ...
					'graphType',	struct( ...
						'options',		{{ str.optionSmithChart, ...
											str.optionLinMag, ...
											str.optionLogMag, ...
											str.optionPhase, ...
											str.optionLinMagPha, ...
											str.optionLogMagPha }}, ...
						'default',		1 ...
						), ...
					'replacement',	struct( ...
						'options',		{{ str.optionReplaceDocked, ...
											str.optionPopNewFig }}, ...
						'default',		1 ...
						), ...
					'marker',		struct( ...
						'options',		str.labelNone, ...
						'default',		1 ...
						) ...
					) ...
				), ...
			'patt',			struct( ...
				'settPanel',	struct( ...
					'title',		str.labelPlotSett, ...
					'graphLabel',	str.labelGraphType, ...
					'firstLabel',	str.labelFirstAxis, ...
					'secondLabel',	struct( ...
						'options',		{{ str.labelSecondAxis, ...
											str.labelOverlayVariable }}, ...
						'default',		2 ...
						), ...
					'fixedLabel',	str.labelFixed, ...
					'polLabel',		str.labelPolarization, ...
					'plotValLabel',	str.labelPlotValue, ...
					'replLabel',	str.labelReplacement, ...
					'overlayLabel',	str.labelOverlayValues, ...
					'noneText',		str.labelNone, ...
					'popButt',		str.buttonPop, ...
					'defButt',		str.buttonDefaults, ...
					'plotButt',		str.buttonPlot ...
					), ...
				'graphPanel',	struct( ...
					'title',		str.labelGraph ...
					), ...
				'annotation',	struct( ...
					'freq',			str.annFrequency, ...
					'phase',		str.annPhase, ...
					'prim',			str.annPrimAng, ...
					'sec',			str.annSecAng, ...
					'linMag',		str.annNormLinMag, ...
					'logMag',		str.annNormLogMag, ...
					'markerFreq',	str.annMarkerFreq, ...
					'markerPhase',	str.annMarkerPhase, ...
					'markerPrim',	str.annMarkerPrim, ...
					'markerSec',	str.annMarkerSec, ...
					'polFixed',		str.annPolFixed ...
					), ...
				'plotSett',		struct( ...
					'graphType',	struct( ...
						'options',		{{ str.optionRectangle, ...
											str.optionPolar, ...
											str.optionContour, ...
											str.optionSurface }}, ...
						'default',		1 ...
						), ...
					'polarization',		struct( ...
						'options',		{{ str.optionHoriz, ...
											str.optionVert, ...
											str.optionSumPowers, ...
											str.optionSumFields }}, ...
						'default',		3 ...
						), ...
					'value',		struct( ...
						'options',		{{ str.optionLinMag, ...
											str.optionLogMag, ...
											str.optionPhase, ...
											str.optionLinMagPha, ...
											str.optionLogMagPha }}, ...
						'default',		1 ...
						), ...
					'replacement',	struct( ...
						'options',		{{ str.optionReplaceDocked, ...
											str.optionPopNewFig }}, ...
						'default',		1 ...
						), ...
					'axis',			struct( ...
						'options',		{{ str.optionPrim, ...
											str.optionSec, ...
											str.optionFreq }}, ...
						'default',		1 ...
						) ...
					) ...
				), ...
			'eff',			struct( ...
				'io',			struct( ...
					'dialogTitle',	str.ioExportDialog, ...	
					'ext',			'*.txt', ...
					'desc',			str.ioFileTypeEff ...
					), ...	
				'settPanel',	struct( ...
					'title',		str.labelPlotSett, ...
					'unitLabel',	str.labelUnit, ...
					'replLabel',	str.labelReplacement, ...
					'popButt',		str.buttonPop, ...
					'defButt',		str.buttonDefaults, ...
					'plotButt',		str.buttonPlot ...
					), ...
				'expPanel',		struct( ...
					'title',		str.labelExport, ...
					'saveLabel',	str.labelSaveEffData, ...
					'expButt',		str.buttonExport ...
					), ...				
				'graphPanel',	struct( ...
					'title',		str.labelGraph ...
					), ...
				'annotation',	struct( ...
					'freq',			str.annFrequency, ...
					'percent',		str.annEffPercent, ...
					'decimal',		str.annEffDecimal, ...
					'decibels',		str.annEffDecibels, ...
					'matching',		str.annEffMatching, ...
					'radiation',	str.annEffRadiation, ...
					'total',		str.annEffTotal ...
					), ...
				'plotSett',		struct( ...
					'unit',	struct( ...
						'options',		{{ str.optionPercent, ...
											str.optionDecimal, ...
											str.optionDecibels }}, ...
						'default',		1 ...
						), ...
					'replacement',	struct( ...
						'options',		{{ str.optionReplaceDocked, ...
											str.optionPopNewFig }}, ...
						'default',		1 ...
						) ...
					) ...
				) ...
			), ...
		'plotting',		struct( ...
			'polar',		struct( ...
				'blocks',		12, ...
				'range',		struct(...
					'lin',			[0 1], ...
					'log',			[-50 0], ...
					'phase',		[-1 1] * 180 ...
					), ...
				'step',			struct(...
					'lin',			0.2, ...
					'log',			10, ...
					'phase',		60 ...
					) ...
				), ...
			'contour',		struct( ...
				'colormap',			brighten(jet(128), 0.5), ...
				'labelSpacing',		1.5 * 72, ...
				'fontWeight',		'bold', ...
				'color',			0 * [1 1 1] ...
				), ...
			'surface',		struct( ...
				'colormap',			jet(128), ...
				'shading',			'faceted' ...
				), ...
			'figName',		struct( ...
				'sParam',		str.annScattTitle, ...
				'patt',			str.annPattTitle, ...
				'eff',			str.annEffTitle ...
				), ...
			'lineStyles',	{{'-', ':', '--', '-.'}}, ...
			'lineColors',	[	0		0		0.8; ...	% blue
								0.8		0		0; ...		% red
								0.2		0.6		0.2; ...	% for. green
								0.6		0		1; ...		% violet
								0.5		0.5		0.5; ...	% grey
								1		0.6		0; ...		% orange
								0		0		0; ...		% black
								0.4		1		0.2; ...	% br. green
								0.6		0.4		0.2; ...	% brown
								0.2		0.8		1; ...		% lt. blue
								1		0		1], ...		% pink
			'lineWidth',		2.5, ...
			'markerSize',		round(7 * [1.3 1 1 1 1.3 1 1 1 1]), ...
			'markerEdgeColor',	0 * [1 1 1], ...
			'markers',			'h^d<pvo>s', ...
			'interpreter',		'tex', ...
			'legendLocation',	'EastOutside' ...
			) ...
		);

end

