function [ s ] = readStrings( l )
% READSTRINGS returns a struct of string literals used by antMeas in the
% requested language

	% Check in/out
	narginchk(0, 1);
	nargoutchk(0, 1);
	
	% Literal translations, one struct for each translation
	t = struct('en', ...
		struct( ...
				... % General
			'winTitle',				'antMeas', ...
			'tabInput',				'Input', ...
			'tabSett',				'Settings', ...
			'tabScatt',				'S-parameters', ...
			'tabPatt',				'Pattern', ...
			'tabEff',				'Efficiency', ...
				... % Buttons
			'buttonOpen',			'Open', ...
			'buttonDefaults',		'Defaults', ...
			'buttonPop',			'Pop', ...
			'buttonPlot',			'Plot', ...
			'buttonExport',			'Export', ...
			'buttonBrowse',			'Browse', ...
			'buttonSave',			'Save', ...
				... % Labels: Common
			'labelNone',			'None', ...
			'labelPlotSett',		'Plot Settings', ...
			'labelGraphType',		'Graph type:', ...
			'labelReplacement',		'Replacement:', ...
			'labelGraph',			'Graph', ...
				... % Options: Common
			'optionLinMag',			'Linear magnitude', ...
			'optionLogMag',			'Logarithmic magnitude', ...
			'optionPhase',			'Phase', ...
			'optionLinMagPha',		'Linear magnitude and phase', ...
			'optionLogMagPha',		'Logarithmic magnitude and phase', ...
			'optionReplaceDocked',	'Replace docked', ...
			'optionPopNewFig',		'Pop new figure', ...
				... % Graph ann.: Common
			'annFrequency',			'Frequency [%s]', ...
			'annPhase',				'Phase [%s]', ...
			'annMarkerFreq',		'Freq: %%g %s', ...
			'annMarkerPhase',		'Phase: %%g %s', ...
				... % IO
			'ioClickToBrowse',		'Click to browse...', ...
			'ioDialogTitle',		'Open the file containing the %s data of the %s antenna', ...
			'ioAntAut',				'measured', ...
			'ioAntRef',				'reference', ...
			'ioMeasHoriz',			'horizontal polarization', ...
			'ioMeasVert',			'vertical polarization', ...
			'ioMeasScatt',			'S-parameter', ...
			'ioMeasEff',			'efficiency', ...
			'ioFileTypePatt',		'DataPro (*.001)', ...
			'ioFileTypeScatt',		'S-parameters (*.s1p)', ...
			'ioFileTypeEff',		'Efficiency file (*.txt)', ...
			'ioExportDialog',		'Select the destination file for exporting', ...
				... % Errors
			'ioErrorEmpty',			'Error: Please define all necessary input files.', ...
			'ioErrorSame',			'Error: Use separate file for each polarization.', ...
			'ioErrorLoad',			'Error: The input files could not be read.', ...
			'ioErrorUnknown',		'Unexpected/unknown error.', ...
				... % Labels: Input tab
			'labelAut',				'Antenna under testing', ...
			'labelRef',				'Reference antenna', ...
			'labelHoriz',			'Horizontal:', ...
			'labelVert',			'Vertical:', ...
			'labelScatt',			'S-parameters:', ...
			'labelEff',				'Efficiency:', ...
				... % Labels: Settings tab
			'labelGlobalUnits',		'Global units', ...
			'labelFrequency',		'Frequency:', ...
			'labelPhase',			'Phase:', ...
			'labelInterp',			'Interpolation', ...
			'labelFunction',		'Function:', ...
			'labelMethod',			'Method:', ...
			'labelMin',				'Minimum:', ...
			'labelMax',				'Maximum:', ...
			'labelStep',			'Step:', ...
			'labelCount',			'Points:', ...
			'labelTotal',			'Total:', ...
			'labelFreqUnit',		'Frequency [%s]:', ...
			'labelPrimUnit',		'Primary angle [%s]:', ...
			'labelSecUnit',			'Secondary angle [%s]:', ...
				... % Options: Settings tab
			'optionHertz',			'Hertz (Hz)', ...
			'optionKilohertz',		'Kilohertz (kHz)', ...
			'optionMegahertz',		'Megahertz (MHz)', ...
			'optionGigahertz',		'Gigahertz (GHz)', ...
			'optionTerahertz',		'Terahertz (THz)', ...
			'optionDegrees',		'Degrees (º)', ...
			'optionRadians',		'Radians (rad)', ...
			'optionNearest',		'Nearest', ...
			'optionLinear',			'Linear', ...
			'optionCubic',			'Cubic', ...
			'optionSpline',			'Spline', ...
			'optionRealImag',		'Real and imaginary', ...
				... % Labels: S-Param tab
			'labelFreqRange',		'Frequency range [%s]:', ...
			'labelMarkerFreq',		'Marker frequencies:', ...
				... % Options: S-Param tab
			'optionSmithChart',		'Smith chart', ...
				... % Graph ann.: S-Param tab
			'annLinMag',			'Magnitude', ...
			'annLogMag',			'Magnitude [dB]', ...
			'annMarkerLinMag',		'Magn: %g', ...
			'annMarkerLogMag',		'Magn: %g dB', ...
			'annScattTitle',		'S-parameters', ...
				... % Labels: Pattern tab
			'labelFirstAxis',		'First axis (i.e., x):', ...
			'labelOverlayVariable',	'Overlay variable:', ...
			'labelSecondAxis',		'Second axis (i.e., y):', ...
			'labelFixed',			'Fixed %s:', ...
			'labelPolarization',	'Polarization:', ...
			'labelPlotValue',		'Plot value (i.e., v):', ...
			'labelOverlayValues',	'Overlay values:', ...
				... % Options: Pattern tab
			'optionFreq',			'Frequency', ...
			'optionPrim',			'Primary angle', ...
			'optionSec',			'Secondary angle', ...
			'optionRectangle',		'Rectangle v = v(x)', ...
			'optionPolar',			'Polar v = v(x)', ...
			'optionContour',		'Filled contour v = v(x, y)', ...
			'optionSurface',		'Surface v = v(x, y)', ...
			'optionHoriz',			'Horizontal', ...
			'optionVert',			'Vertical', ....
			'optionSumPowers',		'Sum powers and mean phase', ...
			'optionSumFields',		'Sum fields', ...
				... % Graph ann.: Patt tab
			'annPrimAng',			'Primary angle [%s]', ...
			'annSecAng',			'Secondary angle [%s]', ...
			'annNormLinMag',		'Normalized magnitude', ...
			'annNormLogMag',		'Normalized magnitude [dB]', ...
			'annMarkerPrim',		'Prim: %%g %s', ...
			'annMarkerSec',			'Sec: %%g %s', ...
			'annPolFixed',			'Polarization: %s, %s', ...
			'annPattTitle',			'Radiation pattern', ...
				... % Labels: Efficiency tab
			'labelExport',			'Export', ...
			'labelSaveEffData',		'Save efficiency data for later use:', ...
			'labelUnit',			'Unit:', ...
				... % Options: Efficiency tab
			'optionPercent',		'Percent (%)', ...
			'optionDecimal',		'Decimal', ...
			'optionDecibels',		'Desibels (dB)', ...
				... % Graph ann.: Patt tab
			'annEffPercent',		'Efficiency [%]', ...
			'annEffDecimal',		'Efficiency', ...
			'annEffDecibels',		'Effciency [dB]', ...
			'annEffMatching',		'Matching', ...
			'annEffRadiation',		'Radiation', ...
			'annEffTotal',			'Total', ...
			'annEffTitle',			'Efficiency' ...
			) ...
		);
	
	% Use 'en' as default 
	if nargin == 1 && isfield(t, lower(l))
		s = t.(lower(l));
	else
		s = t.en;
	end
	
end
